global:
  resolve_timeout: 3m
  smtp_smarthost: 'smtp.exmail.qq.com:465'
  smtp_from: '******@example.com'
  smtp_auth_username: '******@example.com'
  smtp_auth_password: '******'

templates:
  - 'template/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 20m
  receiver: 'webhook'

receivers:
- name: 'email'
  email_configs:
  - to: 'someone@example.com'  # 接收警报的email配置
    require_tls: false
    html: '{{ template "alert.html" . }}' # 设定邮箱的内容模板
    headers: { Subject: "***服务器状态告警提醒"} # 接收邮件的标题
- name: 'webhook'
  webhook_configs:
    - url: 'http://alertmanager-webhook-adapter:8060/webhook/send?channel_type=weixin&token=******'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
