groups:
- name: diskrules
  rules:
  - alert: PartitionGenRunOut
    expr: (1-node_filesystem_avail_bytes{fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"}) > 0.9 
    for: 2m
    labels:
      #team: node
      severity: warning
      action: text
      kind: node_export
    annotations:
      summary: "{{$labels.instance}}: 分区空间占用过高"
      description: "{{$labels.instance}}: {{$labels.job}} 分区空间占用过高 "
      value: "{{humanizePercentage $value}}"
