groups:
  - name: http_down
    rules:
    - alert: HTTP返回非200状态
      expr:  probe_http_status_code != 200
      for: 2m
      labels:
        severity: "error"
      annotations:
        summary: "{{$labels.instance}} : HTTP返回非200状态"
        value: Down
