groups:
- name: loadrules
  rules:
  - alert: ServerLoadTooHigh
    expr: ( node_load5 / count(node_cpu_seconds_total{mode="idle"}) without (cpu,mode) ) > 1.1
    for: 5m
    labels:
      #team: node
      severity: warning
      action: text
      kind: node_export
    annotations:
      summary: "{{$labels.instance}}: load is too high"
      description: "{{$labels.instance}}: job {{$labels.job}} load_5 is overload in last 5min "
      value: "{{$value}}"
